abbr -a -U -- 1 'cd -'
abbr -a -U -- 2 'cd -2'
abbr -a -U -- 3 'cd -3'
abbr -a -U -- 4 'cd -4'
abbr -a -U -- 5 'cd -5'
abbr -a -U -- 6 'cd -6'
abbr -a -U -- 7 'cd -7'
abbr -a -U -- 8 'cd -8'
abbr -a -U -- 9 'cd -9'
abbr -a -U -- - 'cd -'
abbr -a -U -- .. 'cd ../'
abbr -a -U -- ... 'cd ../../'
abbr -a -U -- .3 'cd ../../../'
abbr -a -U -- .4 'cd ../../../../'
abbr -a -U -- .5 'cd ../../../../../'
abbr -a -U -- .6 'cd ../../../../../../'
abbr -a -U -- _ sudo
abbr -a -U -- afind 'ack -il'
abbr -a -U -- alert notify-send\ --urgency,low\ -i\ \"\$\(\[\ \$\?\ ,\ 0\ \]\ \&\&\ echo\ terminal\ \|\|\ echo\ error\)\"\ \"\$\(history\|tail\ -n1\|sed\ -e\ \'s/\^\\s\*\[0-9\]\\+\\s\*//\;s/\[\;\&\|\]\\s\*alert\$//\'\)\"
abbr -a -U -- c clear
abbr -a -U -- cb 'cargo build'
abbr -a -U -- cc 'cargo clean'
abbr -a -U -- cd.. 'cd ../'
abbr -a -U -- cic 'set completion-ignore-case On'
abbr -a -U -- code code-insiders
abbr -a -U -- cp 'cp -iv'
abbr -a -U -- d docker
abbr -a -U -- dc docker-compose
abbr -a -U -- drca 'docker rm `docker ps -a -q`'
abbr -a -U -- dria 'docker rmi -f `docker images -aq`'
abbr -a -U -- drva 'docker volume rm $(docker volume ls -qf dangling,true)'
abbr -a -U -- dsp 'docker system prune'
abbr -a -U -- egrep 'egrep --color,auto'
abbr -a -U -- fgrep 'fgrep --color,auto'
abbr -a -U -- fix_stty 'stty sane'
abbr -a -U -- fix_term echo\ -e\ \"\\033c\"
abbr -a -U -- ga 'git add'
abbr -a -U -- gaa 'git add --all'
abbr -a -U -- gapa 'git add --patch'
abbr -a -U -- gau 'git add --update'
abbr -a -U -- gb 'git branch'
abbr -a -U -- gba 'git branch -a'
abbr -a -U -- gbd 'git branch -d'
abbr -a -U -- gbda git\ branch\ --no-color\ --merged\ \|\ command\ grep\ -vE\ \"\^\(\\\*\|\\s\*\(master\|develop\|dev\)\\s\*\$\)\"\ \|\ command\ xargs\ -n\ 1\ git\ branch\ -d
abbr -a -U -- gbl 'git blame -b -w'
abbr -a -U -- gbnm 'git branch --no-merged'
abbr -a -U -- gbr 'git branch --remote'
abbr -a -U -- gbs 'git bisect'
abbr -a -U -- gbsb 'git bisect bad'
abbr -a -U -- gbsg 'git bisect good'
abbr -a -U -- gbsr 'git bisect reset'
abbr -a -U -- gbss 'git bisect start'
abbr -a -U -- gc 'git commit -v'
abbr -a -U -- gc! 'git commit -v --amend'
abbr -a -U -- gca 'git commit -v -a'
abbr -a -U -- gca! 'git commit -v -a --amend'
abbr -a -U -- gcam 'git commit -a -m'
abbr -a -U -- gcan! 'git commit -v -a --no-edit --amend'
abbr -a -U -- gcans! 'git commit -v -a -s --no-edit --amend'
abbr -a -U -- gcb 'git checkout -b'
abbr -a -U -- gcd 'git checkout develop'
abbr -a -U -- gcf 'git config --list'
abbr -a -U -- gcl 'git clone --recursive'
abbr -a -U -- gclean 'git clean -fd'
abbr -a -U -- gcm 'git checkout master'
abbr -a -U -- gcmsg 'git commit -m'
abbr -a -U -- gcn! 'git commit -v --no-edit --amend'
abbr -a -U -- gco 'git checkout'
abbr -a -U -- gcount 'git shortlog -sn'
abbr -a -U -- gcp 'git cherry-pick'
abbr -a -U -- gcpa 'git cherry-pick --abort'
abbr -a -U -- gcpc 'git cherry-pick --continue'
abbr -a -U -- gcps 'git cherry-pick -s'
abbr -a -U -- gcs 'git commit -S'
abbr -a -U -- gcsm 'git commit -s -m'
abbr -a -U -- gd 'git diff'
abbr -a -U -- gdca 'git diff --cached'
abbr -a -U -- gdct 'git describe --tags `git rev-list --tags --max-count,1`'
abbr -a -U -- gdt 'git diff-tree --no-commit-id --name-only -r'
abbr -a -U -- gdw 'git diff --word-diff'
abbr -a -U -- gf 'git fetch'
abbr -a -U -- gfa 'git fetch --all --prune'
abbr -a -U -- gfo 'git fetch origin'
abbr -a -U -- gg 'git gui citool'
abbr -a -U -- gga 'git gui citool --amend'
abbr -a -U -- ggpull 'git pull origin $(git_current_branch)'
abbr -a -U -- ggpur ggu
abbr -a -U -- ggpush 'git push origin $(git_current_branch)'
abbr -a -U -- ggsup 'git branch --set-upstream-to,origin/$(git_current_branch)'
abbr -a -U -- ghh 'git help'
abbr -a -U -- gignore 'git update-index --assume-unchanged'
abbr -a -U -- gignored 'git ls-files -v | grep "^[[:lower:]]"'
abbr -a -U -- git-svn-dcommit-push 'git svn dcommit && git push github master:svntrunk'
abbr -a -U -- gk \\gitk\ --all\ --branches
abbr -a -U -- gke \\gitk\ --all\ \$\(git\ log\ -g\ --pretty,\%h\)
abbr -a -U -- gl 'git pull'
abbr -a -U -- glg 'git log --stat'
abbr -a -U -- glgg 'git log --graph'
abbr -a -U -- glgga 'git log --graph --decorate --all'
abbr -a -U -- glgm 'git log --graph --max-count,10'
abbr -a -U -- glgp 'git log --stat -p'
abbr -a -U -- glo 'git log --oneline --decorate'
abbr -a -U -- glog 'git log --oneline --decorate --graph'
abbr -a -U -- gloga 'git log --oneline --decorate --graph --all'
abbr -a -U -- glol git\ log\ --graph\ --pretty,\'\%Cred\%h\%Creset\ -\%C\(yellow\)\%d\%Creset\ \%s\ \%Cgreen\(\%cr\)\ \%C\(bold\ blue\)\<\%an\>\%Creset\'\ --abbrev-commit
abbr -a -U -- glola git\ log\ --graph\ --pretty,\'\%Cred\%h\%Creset\ -\%C\(yellow\)\%d\%Creset\ \%s\ \%Cgreen\(\%cr\)\ \%C\(bold\ blue\)\<\%an\>\%Creset\'\ --abbrev-commit\ --all
abbr -a -U -- glp _git_log_prettily
abbr -a -U -- glum 'git pull upstream master'
abbr -a -U -- gm 'git merge'
abbr -a -U -- gmom 'git merge origin/master'
abbr -a -U -- gmt 'git mergetool --no-prompt'
abbr -a -U -- gmtvim 'git mergetool --no-prompt --tool,vimdiff'
abbr -a -U -- gmum 'git merge upstream/master'
abbr -a -U -- gp 'git push'
abbr -a -U -- gpd 'git push --dry-run'
abbr -a -U -- gpoat 'git push origin --all && git push origin --tags'
abbr -a -U -- gpristine 'git reset --hard && git clean -dfx'
abbr -a -U -- gpsup 'git push --set-upstream origin $(git_current_branch)'
abbr -a -U -- gpu 'git push upstream'
abbr -a -U -- gpv 'git push -v'
abbr -a -U -- gr 'git remote'
abbr -a -U -- gra 'git remote add'
abbr -a -U -- grb 'git rebase'
abbr -a -U -- grba 'git rebase --abort'
abbr -a -U -- grbc 'git rebase --continue'
abbr -a -U -- grbi 'git rebase -i'
abbr -a -U -- grbm 'git rebase master'
abbr -a -U -- grbs 'git rebase --skip'
abbr -a -U -- grep 'grep '
abbr -a -U -- grh 'git reset HEAD'
abbr -a -U -- grhh 'git reset HEAD --hard'
abbr -a -U -- grmv 'git remote rename'
abbr -a -U -- grrm 'git remote remove'
abbr -a -U -- grset 'git remote set-url'
abbr -a -U -- grt 'cd $(git rev-parse --show-toplevel || echo ".")'
abbr -a -U -- gru 'git reset --'
abbr -a -U -- grup 'git remote update'
abbr -a -U -- grv 'git remote -v'
abbr -a -U -- gsb 'git status -sb'
abbr -a -U -- gsd 'git svn dcommit'
abbr -a -U -- gsi 'git submodule init'
abbr -a -U -- gsps 'git show --pretty,short --show-signature'
abbr -a -U -- gsr 'git svn rebase'
abbr -a -U -- gss 'git status -s'
abbr -a -U -- gst 'git status'
abbr -a -U -- gsta 'git stash save'
abbr -a -U -- gstaa 'git stash apply'
abbr -a -U -- gstc 'git stash clear'
abbr -a -U -- gstd 'git stash drop'
abbr -a -U -- gstl 'git stash list'
abbr -a -U -- gstp 'git stash pop'
abbr -a -U -- gsts 'git stash show --text'
abbr -a -U -- gsu 'git submodule update'
abbr -a -U -- gts 'git tag -s'
abbr -a -U -- gtv 'git tag | sort -V'
abbr -a -U -- gunignore 'git update-index --no-assume-unchanged'
abbr -a -U -- gunwip git\ log\ -n\ 1\ \|\ grep\ -q\ -c\ \"\\-\\-wip\\-\\-\"\ \&\&\ git\ reset\ HEAD\~1
abbr -a -U -- gup 'git pull --rebase'
abbr -a -U -- gupv 'git pull --rebase -v'
abbr -a -U -- gwch 'git whatchanged -p --abbrev-commit --pretty,medium'
abbr -a -U -- gwip 'git add -A; git rm $(git ls-files --deleted) 2> /dev/null; git commit --no-verify -m "--wip-- [skip ci]"'
abbr -a -U -- l 'ls -lah'
abbr -a -U -- la 'ls -lAh'
abbr -a -U -- less 'less -FSRXc'
abbr -a -U -- ll 'ls -lAFh'
abbr -a -U -- ls 'ls -G'
abbr -a -U -- lsa 'ls -lah'
abbr -a -U -- md 'mkdir -p'
abbr -a -U -- mkdir 'mkdir -pv'
abbr -a -U -- mv 'mv -iv'
abbr -a -U -- nano 'nano -W'
abbr -a -U -- nb 'npm run build'
abbr -a -U -- nd 'npm run dev'
abbr -a -U -- ne 'npm exec'
abbr -a -U -- nodem 'node --experimental-modules'
abbr -a -U -- nodep 'node --optimize_for_size --max_old_space_size,920 --gc_interval,100'
abbr -a -U -- nr 'npm run'
abbr -a -U -- ns 'npm run start'
abbr -a -U -- nt 'npm test'
abbr -a -U -- p 'bm -p'
abbr -a -U -- path echo\ -e\ \$\{PATH//:/\\n\}
abbr -a -U -- please sudo
abbr -a -U -- rd rmdir
abbr -a -U -- s 'bm -a'
abbr -a -U -- show_options shopt
abbr -a -U -- src 'source ~/.bashrc'
abbr -a -U -- tosjis 'nkf -s --overwrite'
abbr -a -U -- toutf8 'nkf -w --overwrite'
abbr -a -U -- up ..
abbr -a -U -- vi vim
abbr -a -U -- wget 'wget -c'
abbr -a -U -- xcurl httpstat
abbr -a -U -- xman tldr
abbr -a -U -- xtop gtop
